apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  project: default

  template:
    metadata:
      name: myapp
      annotations:
        argocd-image-updater.argoproj.io/image-list: myappr=stykle/learningacrgocd
        argocd-image-updater.argoproj.io/myalias.force-update: true
        argocd-image-updater.argoproj.io/write-back-method: git
      finalizers:
        - resources-finalizer.argocd.argoproj.io

  source:
    repoURL: 'https://github.com/Rufus100Procent/LearningArgoCd.git'
    targetRevision: HEAD
    path: kubernates

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false  # Optional: Prevents auto-syncing when there are no changes
