apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
  annotations:
    argocd-image-updater.argoproj.io/image-list: demo-app-container=stykle/learningacrgocd
    argocd-image-updater.argoproj.io/demo-app-container.update-strategy: latest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: demo-app-container
          image: stykle/learningacrgocd:v0.2.0
          ports:
            - containerPort: 8080
