name: Java CI with Maven and Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Extract Semantic Version from Commit or Tag
        id: extract_version
        run: |
          # Check for the latest tag
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          
          # If no tag exists, try to extract from commit message and tag it
          if [[ -z "$TAG" ]]; then
            COMMIT_MSG=$(git log -1 --pretty=%B)
            VERSION=$(echo $COMMIT_MSG | grep -oE '^[3-4]\.[0-9]+\.[0-9]+')
          
            if [[ -n "$VERSION" ]]; then
              git tag -a "v$VERSION" -m "Version $VERSION"
              git push origin "v$VERSION"
              echo "Tagged the commit with v$VERSION"
              echo "VERSION=$VERSION" >> $GITHUB_ENV
            else
              echo "No valid version found in commit message. Skipping Docker build and push."
              exit 0
            fi
          else
            VERSION=$(echo $TAG | grep -oE '^[vVrR]?[3-4]\.[0-9]+\.[0-9]+')
            if [[ -z "$VERSION" ]]; then
              echo "No valid semantic version (3.x.x or 4.x.x) found in the latest tag. Skipping Docker build and push."
              exit 0
            fi
            VERSION=$(echo $VERSION | sed 's/^[vVrR]//')
            echo "VERSION=$VERSION" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Log in to Docker Hub
        if: env.VERSION
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build the Docker image
        if: env.VERSION
        run: docker build -t stykle/learningacrgocd:${{ env.VERSION }} .

      - name: Push the Docker image
        if: env.VERSION
        run: docker push stykle/learningacrgocd:${{ env.VERSION }}
