name: Java CI with Maven and Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Extract Semantic Version from Commit Message
        id: extract_version
        run: |
          # Extract version from commit message
          COMMIT_MSG=$(git log -1 --pretty=%B)
          VERSION=$(echo "$COMMIT_MSG" | grep -oE '^[3-9]\.[0-9]+\.[0-9]+')

          # Check if a valid version was found
          if [[ -z "$VERSION" ]]; then
            echo "No valid semantic version (3.x.x or higher) found in the commit message. Skipping Docker build and push."
            exit 0
          fi

          # Set the version as an environment variable
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        shell: bash

      - name: Set Git User for Tagging
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
        shell: bash

      - name: Log in to Docker Hub
        if: env.VERSION
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build the Docker image
        if: env.VERSION
        run: docker build -t stykle/learningacrgocd:${{ env.VERSION }} .

      - name: Push the Docker image
        if: env.VERSION
        run: docker push stykle/learningacrgocd:${{ env.VERSION }}
